### ISSUE TITLE
Template "default.html.twig" is not defined

### ISSUE THREAD

**Issue by Quy** [getgrav/grav-theme-boxify#1]
Using `develop` of grav and boxify.
```
 RuntimeException (400)
Template "default.html.twig" is not defined.
```

**Comment by flaviocopes** [comment]
This is not an issue. Every theme chooses to support some page types.

Boxify is a single, modular page theme and does not support the default page type, as it's not present here: https://github.com/getgrav/grav-theme-boxify/tree/develop/templates

Like Learn2 for example, which choose to support only documentation pages.
